import { useState } from 'react'
import { ArrowLeft, CheckCheck, LockKeyhole, RefreshCw, ShieldCheck, Sparkles, TriangleAlert } from 'lucide-react'
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Checkbox } from '@/components/ui/checkbox'
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog'
import { Label } from '@/components/ui/label'
import { Separator } from '@/components/ui/separator'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { ActivityList, StatusBadge } from '@/components/request-table'
import { canApprove, errorText, isRealVerified, label, money, snapshotMatches, timestamp } from '@/lib/refunds'
import type { ApprovalSnapshot, RefundCase, Session } from '@/types'

function Fact({ label: name, children }: { label: string; children: React.ReactNode }) {
  return <div className="min-w-0"><dt className="text-xs text-muted-foreground">{name}</dt><dd className="mt-1.5 break-words text-sm font-medium">{children}</dd></div>
}

export function CaseDetail({ record, session, busy, blocked, onBack, onReview, onApprove, onRefresh, onReload }: {
  record: RefundCase; session: Session; busy: boolean; blocked: boolean; onBack: () => void
  onReview: () => void; onApprove: (snapshot: ApprovalSnapshot) => Promise<void>; onRefresh: () => void; onReload: () => void
}) {
  const [snapshot, setSnapshot] = useState<ApprovalSnapshot | null>(null)
  const [checked, setChecked] = useState(false)
  const review = record.latest_review
  const payment = record.operation
  const approvable = canApprove(record) && !blocked
  const reviewable = record.can_review && typeof record.item_used === 'boolean' && !payment && !blocked
  const validDialog = snapshot !== null && snapshotMatches(snapshot, record) && !blocked
  const errors = [...(review?.errors || []), ...(review?.error ? [review.error] : [])].map(errorText)
  const operator = session.approval_mode === 'test_operator'
  return <div className="space-y-6">
    <Button variant="ghost" size="sm" onClick={onBack} disabled={busy} className="-ml-2"><ArrowLeft className="size-4" aria-hidden />All requests</Button>
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><div className="mb-2 flex flex-wrap items-center gap-2"><h1 className="text-2xl font-semibold tracking-tight">Refund request</h1><StatusBadge state={record.state} /></div><p className="break-all font-mono text-xs text-muted-foreground">Capture {record.capture_id}</p></div><div className="sm:text-right"><p className="text-3xl font-semibold tracking-tight tabular-nums">{money(record.amount_minor, record.currency)}</p><p className="mt-1 text-xs text-muted-foreground">USD · sandbox funds</p></div></div>
    {record.error && <Alert variant="destructive"><TriangleAlert /><AlertTitle>Request needs attention</AlertTitle><AlertDescription>{errorText(record.error)}</AlertDescription></Alert>}
    {blocked && <Alert><TriangleAlert /><AlertTitle>Reload before another action</AlertTitle><AlertDescription>The previous action did not return a confirmed result. Reload the saved request to inspect its state. No repeat submission is available.<Button variant="outline" size="sm" onClick={onReload} disabled={busy} className="mt-3">Reload saved request</Button></AlertDescription></Alert>}
    <div className="grid items-start gap-6 xl:grid-cols-[minmax(0,1fr)_320px]">
      <Tabs defaultValue="evidence" className="min-w-0 gap-4"><TabsList className="w-full justify-start sm:w-auto"><TabsTrigger value="evidence">Evidence</TabsTrigger><TabsTrigger value="assessment">AI assessment</TabsTrigger><TabsTrigger value="activity">Activity</TabsTrigger></TabsList>
        <TabsContent value="evidence" className="space-y-5"><Card><CardHeader><div className="flex flex-wrap items-center justify-between gap-2"><CardTitle>Payment evidence</CardTitle><Badge variant="outline" className={record.transaction_verified_by_service ? 'border-emerald-200 bg-emerald-50 text-emerald-800' : 'border-amber-200 bg-amber-50 text-amber-900'}>{record.transaction_verified_by_service ? 'PayPal sandbox' : 'Synthetic transport'}</Badge></div><CardDescription>Payment facts fetched by the server.</CardDescription></CardHeader><CardContent><dl className="grid gap-x-8 gap-y-6 sm:grid-cols-2"><Fact label="Captured amount">{money(record.amount_minor, record.currency)}</Fact><Fact label="Purchase date (UTC)">{record.purchase_date}</Fact><Fact label="Capture ID"><span className="font-mono text-xs">{record.capture_id}</span></Fact><Fact label="Last payment check">{timestamp(record.capture_read_at)}</Fact></dl></CardContent></Card>
          <Card><CardHeader><CardTitle>Merchant-supplied information</CardTitle><CardDescription>Physical condition and customer text are separate from PayPal’s payment evidence.</CardDescription></CardHeader><CardContent className="space-y-5"><dl className="grid gap-5 sm:grid-cols-2"><Fact label="Item condition">{record.item_used === false ? 'Unused · merchant confirmed' : record.item_used === true ? 'Used · merchant confirmed' : 'Not confirmed'}</Fact><Fact label="Request received (UTC)">{record.request_date}</Fact></dl><Separator /><div><p className="mb-2 text-xs font-medium text-muted-foreground">Customer message · untrusted text</p><p className="whitespace-pre-wrap break-words rounded-lg border bg-muted/40 px-4 py-3 text-sm leading-relaxed">{record.customer_message}</p></div></CardContent></Card>
          <Card><CardHeader><CardTitle>Policy snapshot</CardTitle><CardDescription className="break-all font-mono text-xs">{record.policy.version}</CardDescription></CardHeader><CardContent className="space-y-4">{Object.entries(record.policy.clauses).map(([id, quote]) => <div key={id} className="flex gap-3"><Badge variant="outline" className="mt-0.5 h-fit shrink-0 font-mono text-[10px]">{id}</Badge><p className="text-sm leading-relaxed text-muted-foreground">{quote}</p></div>)}</CardContent></Card>
        </TabsContent>
        <TabsContent value="assessment"><Card><CardHeader><div className="flex items-center gap-2"><Sparkles className="size-4 text-primary" aria-hidden /><CardTitle>AI assessment</CardTitle></div><CardDescription>The original recommendation, exact policy quotes, and validation results.</CardDescription></CardHeader><CardContent className="space-y-5">{review ? <>
          <div className="rounded-lg border bg-muted/30 p-4"><p className="text-xs font-medium text-muted-foreground">{review.accepted_recommendation ? 'Accepted recommendation' : 'Assessment not accepted'}</p><h2 className="mt-1 text-lg font-semibold">{review.accepted_recommendation ? label(review.accepted_recommendation) : 'Review incomplete'}</h2><p className="mt-3 whitespace-pre-wrap text-sm leading-relaxed">{review.rationale || 'No complete AI rationale was returned.'}</p></div>
          {review.citations.map((citation, index) => <blockquote key={`${citation.id}-${index}`} className="border-l-2 border-primary/40 pl-4"><p className="text-sm leading-relaxed">“{citation.quote}”</p><cite className="mt-2 block text-xs not-italic text-muted-foreground">{citation.id} · {record.policy.clauses[citation.id] === citation.quote ? 'Exact policy quote' : 'Quote does not match policy'}</cite></blockquote>)}
          {errors.length > 0 && <Alert variant="destructive"><TriangleAlert /><AlertTitle>Validation stopped this review</AlertTitle><AlertDescription><ul className="list-disc space-y-1 pl-4">{[...new Set(errors)].map(error => <li key={error}>{error}</li>)}</ul></AlertDescription></Alert>}
          {review.missing_information.length > 0 && <p className="text-sm text-muted-foreground">Information requested: {review.missing_information.join(', ')}</p>}
          <Separator /><div className="flex flex-wrap gap-x-5 gap-y-2 text-xs text-muted-foreground"><span>{review.runtime_provenance === 'local_ollama' ? 'Local Ollama' : review.runtime_provenance === 'injected_test_generator' ? 'Injected test response' : 'Runtime not recorded'}</span><span>{review.model_calls} model request(s)</span><span>{review.completed_model_responses} completed response(s)</span></div>
        </> : <div className="py-8 text-center"><Sparkles className="mx-auto mb-3 size-7 text-muted-foreground/60" aria-hidden /><h3 className="text-sm font-medium">Ready to assess this request</h3><p className="mx-auto mt-2 max-w-sm text-sm text-muted-foreground">The local model reads the saved policy and transaction evidence. It does not authorize a refund.</p><Button className="mt-5" onClick={onReview} disabled={busy || !reviewable}>Run AI assessment</Button></div>}</CardContent></Card></TabsContent>
        <TabsContent value="activity"><Card className="gap-0 overflow-hidden py-0"><CardHeader className="border-b py-5"><CardTitle>Immutable activity record</CardTitle><CardDescription>Saved actions and status changes for this capture.</CardDescription></CardHeader><ActivityList records={[record]} /></Card></TabsContent>
      </Tabs>
      <Card className="xl:mt-12"><CardHeader><div className="flex items-center gap-2"><ShieldCheck className="size-4 text-primary" aria-hidden /><CardTitle>Decision & result</CardTitle></div><CardDescription>Explicit approval. One refund. A separate status check.</CardDescription></CardHeader><CardContent className="space-y-5">
        {payment ? <><div className="rounded-lg border bg-muted/30 p-4"><StatusBadge state={payment.state} /><p className="mt-3 text-sm leading-relaxed">{payment.state === 'verified' ? isRealVerified(record) ? 'The sandbox refund was independently verified against the approved capture and amount.' : 'Verified with synthetic transport evidence. This is not a PayPal refund.' : payment.state === 'uncertain' ? 'The outcome is uncertain. Do not submit another refund.' : payment.state === 'pending' ? 'PayPal returned a receipt. Check the refund separately to verify completion.' : payment.state === 'prepared' ? 'Approval is recorded. No refund submission has been claimed.' : payment.state === 'failed' ? 'The recorded request failed. This screen does not submit another refund for this capture.' : 'The submission is in progress or requires reconciliation. Do not repeat it.'}</p></div>
          <dl className="space-y-4"><Fact label="PayPal refund status">{payment.provider_status || 'Not read back'}</Fact><Fact label="Refund ID"><span className="font-mono text-xs">{payment.refund_id || 'Not yet known'}</span></Fact><Fact label="Approval attribution">{payment.approval.approval_kind === 'test_operator' ? 'Test operator' : 'Human interface'} · {payment.approval.approved_by}</Fact><Fact label="Approved at">{timestamp(payment.approval.approved_at)}</Fact></dl>
          {payment.last_error && <Alert variant="destructive"><AlertDescription>{errorText(payment.last_error)}</AlertDescription></Alert>}
          {['pending', 'uncertain'].includes(payment.state) && payment.refund_id && <Button variant="outline" className="w-full" onClick={onRefresh} disabled={busy}><RefreshCw className="size-4" aria-hidden />Check PayPal status</Button>}
          {['submitting', 'uncertain'].includes(payment.state) && !payment.refund_id && <p className="text-xs leading-relaxed text-muted-foreground">No refund ID is known. Reconcile the existing request in PayPal; automatic resubmission is disabled.</p>}
        </> : <><div className="flex gap-2.5 rounded-lg bg-muted p-3"><LockKeyhole className="mt-0.5 size-4 shrink-0 text-muted-foreground" aria-hidden /><p className="text-xs leading-relaxed text-muted-foreground">AI recommends. You review the evidence and approve the exact amount before any refund is sent.</p></div>{reviewable && <Button variant="outline" className="w-full" onClick={onReview} disabled={busy}><Sparkles className="size-4" aria-hidden />{review ? 'Run a new assessment' : 'Run AI assessment'}</Button>}{review?.accepted_recommendation === 'decline' && <p className="text-sm text-muted-foreground">The accepted recommendation is to decline. Refund approval is unavailable.</p>}</>}
        {approvable && <Dialog open={validDialog} onOpenChange={open => { setChecked(false); setSnapshot(open ? { caseId: record.id, captureId: record.capture_id, amountMinor: record.amount_minor, currency: record.currency, reviewHash: record.latest_review!.review_hash! } : null) }}><DialogTrigger asChild><Button className="w-full" disabled={busy}><CheckCheck className="size-4" aria-hidden />Review refund approval</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Approve {snapshot ? money(snapshot.amountMinor, snapshot.currency) : ''} sandbox refund</DialogTitle><DialogDescription>{busy ? 'The refund request is processing. Closing this dialog does not cancel it. Its status remains visible on the request.' : 'This submits one refund against the exact payment and assessment shown below.'}</DialogDescription></DialogHeader>{snapshot && <>
          <dl className="grid gap-4 rounded-lg border bg-muted/30 p-4"><Fact label="Captured payment"><span className="font-mono text-xs">{snapshot.captureId}</span></Fact><Fact label="Refund amount">{money(snapshot.amountMinor, snapshot.currency)} USD · sandbox</Fact><Fact label="Assessment saved">{timestamp(review?.finished_at)}</Fact><Fact label="Policy version"><span className="break-all text-xs">{record.policy.version}</span></Fact></dl>
          {operator && <Badge variant="outline" className="w-fit border-amber-200 bg-amber-50 text-amber-900">Test operator approval</Badge>}
          <div className="flex items-start gap-3 py-2"><Checkbox id="approve-confirm" checked={checked} onCheckedChange={value => setChecked(value === true)} disabled={busy} /><Label htmlFor="approve-confirm" className="block text-sm font-normal leading-relaxed">{operator ? 'As a test operator, I' : 'I'} reviewed the payment, policy, and AI assessment and approve this exact sandbox refund.</Label></div>
          <DialogFooter><Button variant="outline" onClick={() => setSnapshot(null)}>{busy ? 'Close' : 'Cancel'}</Button><Button disabled={!checked || busy || !snapshotMatches(snapshot, record)} onClick={async () => { if (!checked || busy || !snapshotMatches(snapshot, record)) return; const frozen = snapshot; setChecked(false); await onApprove(frozen); setSnapshot(null) }}>Approve and refund {money(snapshot.amountMinor, snapshot.currency)} sandbox</Button></DialogFooter>
        </>}</DialogContent></Dialog>}
        {!payment && !approvable && <p className="text-xs text-muted-foreground">Approval becomes available after a complete, eligible refund assessment.</p>}
      </CardContent></Card>
    </div>
  </div>
}
